1004 fix datepicker corrected month and year navigation buttons
Brisanet/ion pull request #1006
Opened 2024-01-15 12:42 UTC by larissa-kamily-brisa

## Issue Number

fix #1004 

## Description
 Now the calendar actions are having the expected behavior.

## Proposed Changes

- replace doCheck with OnChanges

## Screenshots

- Before:

[Gravação de tela de 2024-01-12 14-31-47.webm](https://github.com/Brisanet/ion/assets/138057627/47cfd80e-bb04-4626-9c21-9e0dd3f357c3)

- After: 

[Gravação de tela de 2024-01-15 09-36-14.webm](https://github.com/Brisanet/ion/assets/138057627/505b0553-4202-4fc5-b7e2-a3993ac3c38e)

## View Storybook

## Compliance

- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code.

2024-01-15 13:26 UTC, wermeson-lopes-brisa approved these changes

2024-01-15 13:32 UTC, deeved-hiuston-brisa approved these changes

2024-01-17 12:54 UTC, larissa-kamily-brisa commented on projects/ion/src/lib/utils/datePicker.ts
> +export function isBetweenRange(currentDay: Day, selectedDays: Day[]): boolean {
created :smile:

2024-01-19 12:28 UTC, iurynogueira requested changes

2024-01-19 12:28 UTC, iurynogueira commented on projects/ion/src/lib/utils/datePicker.spec.ts
> +  });
```suggestion
  describe('isToday', () => {
    let currentDate: Day;
    const lang = 'pt-BR';

    it('should return true if day is today', () => {
      currentDate = new Day(today);
      result = isToday(currentDate, lang);
      expect(result).toBe(true);
    });
    
    it('should return false if day is not today', () => {
      currentDate = new Day(new Date('2024-01-03'));
      result = isToday(currentDate, lang);
      expect(result).toBe(false);
    });
  });
```

lang not is modified, so we can use const

2024-01-22 12:11 UTC, merged