fix: modal service close
Brisanet/ion pull request #1014
Opened 2024-01-23 13:19 UTC by pedro-martins-brisa

Previously, the modal service allowed only one reference, resulting in the replacement of the first modal when opening a second one. Now, with the refactoring, the service operates with an array of modals, preserving individual references. This prevents conflicts, enabling the simultaneous opening of multiple modals without losing control over each one. The update makes the service more flexible and adaptable to scenarios with multiple modals.

2024-01-24 19:54 UTC, wermeson-lopes-brisa approved these changes

2024-01-25 11:22 UTC, vinicius-guedes-brisa approved these changes

2024-01-25 12:31 UTC, danilo-moreira-brisa approved these changes

2024-01-26 13:33 UTC, iurynogueira requested changes

2024-01-26 13:33 UTC, iurynogueira commented on projects/ion/src/lib/modal/modal.service.ts
> +  private get modalComponentControl(): ModalComponentControl {
currecntComponentControl

2024-02-06 17:29 UTC, merged