feat: select predefined period on date range picker
Brisanet/ion pull request #1015
Opened 2024-01-23 19:38 UTC by larissa-kamily-brisa

## Issue Number

#912 

## Description

It 's  now possible to select predefined period ranges
The definition of these periods is done dynamically, the developer chooses according to the needs of the project.

## Screenshots
[Gravação de tela de 2024-01-23 16-34-09.webm](https://github.com/Brisanet/ion/assets/138057627/8bc93c73-bcd9-469d-b0b1-e1f0c2106a0d)

## Compliance

- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code.

2024-01-24 13:10 UTC, deeved-hiuston-brisa commented on projects/ion/src/lib/picker/date-picker/date-picker.component.spec.ts
> +  });
Implement tests for 15 and 30 day options.

2024-01-24 13:18 UTC, deeved-hiuston-brisa commented
Good job! This feature will help us a lot.

2024-01-24 14:41 UTC, iurynogueira requested changes
Nice work @larissa-kamily-brisa

2024-01-24 14:41 UTC, iurynogueira commented on projects/ion/src/lib/picker/date-picker/date-picker-calendar/date-picker-calendar.component.ts
> +  @Input() selectedDay: Day[] = [];
```suggestion
  @Input() selectedDays: Day[] = [];
```

2024-01-24 14:41 UTC, iurynogueira commented on projects/ion/src/lib/picker/date-picker/date-picker-calendar/date-picker-calendar.component.ts
> +    arrangeDates(this.selectedDay);
```suggestion
    arrangeDates(this.selectedDay);
```

Check length this.selectedDay before

2024-01-24 14:41 UTC, iurynogueira commented on projects/ion/src/lib/picker/date-picker/date-picker.component.ts
> +  selectedDay: Day[] = [];
```suggestion
  selectedDays: Day[] = [];
```

2024-01-24 17:41 UTC, deeved-hiuston-brisa approved these changes

2024-01-25 12:42 UTC, wermeson-lopes-brisa approved these changes

2024-01-26 13:34 UTC, iurynogueira approved these changes

2024-01-26 13:34 UTC, merged