Create breadcrumbs #448
Brisanet/ion pull request #455
Opened 2023-02-15 13:54 UTC by larissacard

## Description

Changing breadcrumb component with new design and emitting event when selected instead of redirecting to new page

## How to Test

New teste called 'should emit the selected breadcrumb' that tests if a event is emitted when a breadcrumb is selected

## Screenshots

New design
![breadcrumb](https://user-images.githubusercontent.com/106749260/219045063-1849a317-bc15-423f-bce7-69840b583bfc.png)

## Compliance

- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code.

2023-02-15 17:30 UTC, Deeved commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.scss
```suggestion
cursor: pointer;
```

2023-02-15 17:31 UTC, Deeved commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.scss
> +.ol-navigator li:last-child {
```suggestion
.ol-navigator li:last-child {
a {
    color: $primary-6;
    font-weight: 600;
    cursor: text;
  }
```

2023-02-15 18:09 UTC, Deeved commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.ts
> +    this.selectedBread.emit(item);
you don't need to emit event when item is last

2023-02-15 18:12 UTC, Deeved commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.html
> +    <li *ngFor="let breadcrumb of breadcrumbs; let index = index">
is not being used
```suggestion
<li *ngFor="let breadcrumb of breadcrumbs;">
```

2023-02-15 18:42 UTC, Deeved commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.spec.ts
> +    expect(selectEvent).toBeCalledWith(config);
``

2023-02-15 18:44 UTC, Deeved commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.spec.ts
> +  it('should emit the selected breadcrumb', async () => {
```suggestion
  it('should emit the selected breadcrumb', async () => {
    await sut();
    const [firstItem] = items;
    const element = screen.getByText(firstItem.label);
    expect(element).toBeInTheDocument();
    fireEvent.click(element);
    expect(selectEvent).toBeCalledWith(firstItem);
  });
  
```

2023-02-23 13:29 UTC, Deeved commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.ts
> +  onSelected(item: BreadcrumbItem) {
```suggestion
  onSelected(item: BreadcrumbItem): void {
```

2023-02-23 13:37 UTC, Deeved approved these changes

2023-02-28 12:28 UTC, iurynogueira requested changes
Great! Thanks for your contribution! 😄

2023-02-28 12:28 UTC, iurynogueira commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.spec.ts
> +    expect(element).toBeInTheDocument();
```suggestion
```

You can remove this because you not are testing this

2023-02-28 12:28 UTC, iurynogueira commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.spec.ts
> +    expect(element).toBeInTheDocument();
same here

2023-02-28 12:28 UTC, iurynogueira commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.spec.ts
> +    expect(element).toBeInTheDocument();
```suggestion
```

2023-03-09 12:16 UTC, iurynogueira approved these changes

2023-03-09 12:16 UTC, merged