fix: adding width parameter in configuration
Brisanet/ion pull request #530
Opened 2023-03-28 19:30 UTC by MarcosOliveir4

2023-03-28 19:43 UTC, luccskywalker requested changes

2023-03-28 19:46 UTC, wermesonsl approved these changes

2023-03-28 19:47 UTC, mizek1 requested changes

2023-03-28 19:47 UTC, mizek1 commented on projects/ion/src/lib/modal/component/modal.component.html
> +      [style.width.px]="configuration.width || 500"
```suggestion
      [style.width.px]="configuration.width || DEFAULT_WIDTH"
```
You can name this value on your component.

2023-03-28 19:53 UTC, luccskywalker approved these changes

2023-03-28 19:55 UTC, wermesonsl approved these changes

2023-03-28 20:28 UTC, iurynogueira approved these changes

2023-03-28 20:37 UTC, mizek1 requested changes

2023-03-28 20:37 UTC, mizek1 commented on projects/ion/src/lib/modal/component/modal.component.ts
>      overlayCanDismiss: true,
```suggestion
  private _defaultModal: IonModalConfiguration = {
    title: 'Ion Modal',
    showOverlay: true,
    overlayCanDismiss: true,
```
You're not using this anymore.

2023-03-29 12:25 UTC, wermesonsl approved these changes

2023-03-29 19:25 UTC, mizek1 approved these changes

2023-03-29 19:25 UTC, merged