Refactor chip dropdown autoclose
Brisanet/ion pull request #541
Opened 2023-03-30 19:58 UTC by Deeved

## Description

chip with dropdown
![chip with dropdown](https://user-images.githubusercontent.com/64809323/228949735-552766fc-1e4b-4260-bb6a-33cde41d6199.gif)

chip without dropdown
![chip without dropdown](https://user-images.githubusercontent.com/64809323/228950122-0a79c2d3-5c17-43a4-8292-370d161325fd.gif)

2023-03-30 20:29 UTC, MarcosOliveir4 approved these changes

2023-03-31 11:47 UTC, AlyssonMascarenhas approved these changes
ITS BEAUTIFUL! 
Good job <3

2023-04-05 12:02 UTC, iurynogueira approved these changes

2023-04-06 16:38 UTC, AlyssonMascarenhas approved these changes

2023-04-06 17:53 UTC, iurynogueira approved these changes

2023-04-11 17:48 UTC, iurynogueira requested changes

2023-04-11 17:48 UTC, iurynogueira commented on projects/ion/src/lib/chip/chip.component.ts
> +  @Input() disableVisibilityToggle = false;
Maybe change to a affirmative will better.

2023-04-12 14:44 UTC, iurynogueira approved these changes

2023-04-14 18:59 UTC, iurynogueira commented
> ![gandalf](https://user-images.githubusercontent.com/60994870/231495007-044e20c2-d0d7-4e97-8548-02ecf1c0daea.gif)

Surrupiou meu gif

2023-04-14 19:43 UTC, merged