fix: padding in breadcrumb (#533)
Brisanet/ion pull request #546
Opened 2023-04-03 12:11 UTC by Lucassec1

I removed the padding from 'breadcrumbs-nav' and 'ol-navigator li a', in a fork I tested these changes with the table component and these were the results.

![image](https://user-images.githubusercontent.com/106749169/229504208-e44dc68b-54ab-450a-9cb1-c2b903cd73af.png)
![image](https://user-images.githubusercontent.com/106749169/229504317-43a079a0-a6fe-4994-b540-9b4c44478252.png)

I created a draft, can you check if these changes are enough? @wermesonsl

2023-04-03 12:42 UTC, wermesonsl requested changes

2023-04-03 13:06 UTC, Lucassec1 commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.scss
> -  padding: spacing(1.25);
I put the paddings again, I removed the padding from ol-navigator, but a 40px padding appeared on the left, do I remove it?
I also removed the padding from extremes sides.

2023-04-04 11:32 UTC, Lucassec1 commented on projects/ion/src/lib/breadcrumb/breadcrumb.component.scss
> -  padding: spacing(1.25);
@wermesonsl can see the changes? i needed to add a padding 0 in ol-navigator, because without it, i had a fixed padding of 40px.

2023-04-04 14:39 UTC, Lucassec1 reviewed
@wermesonsl can see the changes? i needed to add a padding 0 in ol-navigator, because without it, i had a fixed padding of 40px.

2023-04-05 16:22 UTC, wermesonsl requested changes

2023-04-14 18:31 UTC, iurynogueira commented
Working in progress?

2023-04-14 18:59 UTC, wermesonsl approved these changes

2023-04-25 13:24 UTC, mizek1 approved these changes
I checked on my project and it looks very nice, thank you for the fix.

![image](https://user-images.githubusercontent.com/57760325/234290307-981830f5-bb99-4df4-93d1-9fc47e583967.png)

2023-04-28 19:55 UTC, merged