Feature/ion select
Brisanet/ion pull request #583
Opened 2023-04-10 11:51 UTC by Deeved

## Description

Add select component

## Proposed Changes

- select component
- tests
- stories

## How to Test

it is possible to test through the storybook, npm link or by making a copy of the build from the feature/ion-select branch and pasting it into the project. After that, just import the IonSelectModule into the module file and then use the ion-select tag in your template

## Screenshots

Include screenshots or GIFs that illustrate the proposed changes. This can be especially useful for user interface changes.
![ion-select](https://user-images.githubusercontent.com/64809323/230895963-9d65ddc4-e0fc-4590-b582-9874f3904c2e.gif)

2023-04-10 14:51 UTC, iurynogueira requested changes

2023-04-10 14:51 UTC, iurynogueira commented on projects/ion/src/lib/select/select.component.ts
> +    );
```suggestion
    const hasSelectedOptions = this.options.some(
      (option) => option.selected === true
    );
```

This is better like a function

2023-04-10 15:03 UTC, MarcosOliveir4 commented
I realized that when the select is clicked after opening it does not close, only when it is clicked outside is this behavior correct?

https://user-images.githubusercontent.com/60994870/230927850-6833e6d5-b23e-4058-b321-7622128b1685.mp4

2023-04-10 22:19 UTC, Deeved commented
@MarcosOliveir4 was solved! Thanks for the observation. 👍🏼

2023-04-11 13:57 UTC, AlyssonMascarenhas approved these changes

2023-04-28 14:32 UTC, merged