feat: ellipsis in pagination component (#512) (#591)
Brisanet/ion pull request #597
Opened 2023-04-13 14:19 UTC by iurynogueira

Description in #591

@jairochaves2

2023-04-13 18:38 UTC, wermesonsl requested changes

2023-04-13 18:38 UTC, wermesonsl commented on projects/ion/src/lib/pagination/pagination.component.spec.ts
> +    const pageZero = screen.getByTestId('page-0');
Se não me engano, estes ID's de testes são gerados com base no número da página. Como esses números iniciam a partir de 1, acredito que seria interessante capturar um page-1 ao invés de page-0.

2023-04-13 18:38 UTC, wermesonsl commented on projects/ion/src/lib/pagination/pagination.component.ts
> +      this.previousNextQuantity = 2;
O que esse número 2 representa? Seria bom pôr ele em uma contante também, com um nome descritivo.

2023-04-13 18:38 UTC, wermesonsl commented on projects/ion/src/lib/pagination/utils/ellipsis.component.ts
> +    else if (pageNumber === this.paginationComponent.pages.length - 2)
Nesse caso o else não é necessário, pois, se o primeiro if for false, ele verificar o segundo de qualquer forma. Se o primeiro for true, como há um return, ele não ira verificar o restante do código da função.

2023-04-13 18:38 UTC, wermesonsl commented on projects/ion/src/lib/pagination/utils/ellipsis.component.ts
> +    } else if (index === qtdOfPages - 1) {
A menos que qtdOfPages - 1 tenha chances de também ser igual a 1, não há necessidade deste else aqui, pois parecem ser condições que não interferem uma na outra.

2023-04-13 18:38 UTC, wermesonsl commented on projects/ion/src/lib/pagination/utils/ellipsis.component.ts
> +      firstPages: firstPages,
como o nome da variável de destino e a de origem são iguais, experimenta deixar apenas uma palavra. Normalmente, o código já entende que elas possuem o mesmo nome:

```
return {
    leftLimit,
    showLeftElipsis,
    firstPages,
}
```

2023-06-05 12:44 UTC, mizek1 commented
Already done in #678.

2023-06-05 12:44 UTC, closed without merging