fix: tab group direction changes according to the border direction
Brisanet/ion pull request #601
Opened 2023-04-13 15:08 UTC by dayannebugarim

## Description

The direction of the borders is limited to the horizontal direction (only top or bottom) and vertical direction (only right or left). Now, the direction of the tab group also changes according to the direction of the border and default values are assigned to the border when the specified value is not accepted for the direction (bottom for horizontal direction and right for vertical direction).

## Screenshots
https://user-images.githubusercontent.com/81201377/231884647-4e5afa28-2cd2-4954-8a75-b64074607e59.mp4

## Compliance

- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code.

2023-04-14 17:28 UTC, mizek1 requested changes

2023-04-14 17:28 UTC, mizek1 commented on projects/ion/src/lib/tab-group/tab-group.component.ts
> +    return directions[border] as DirectionType;
You can type directions object this way to remove the `as` assertion on return:
```suggestion
  private getDirectionByBorder(border: BorderDirectionType): DirectionType {
    const directions: {
      [key in BorderDirectionType]: DirectionType;
    } = {
      left: 'vertical',
      right: 'vertical',
      top: 'horizontal',
      bottom: 'horizontal',
    };

    return directions[border];
```

2023-04-14 17:28 UTC, mizek1 commented on projects/ion/src/lib/tab-group/tab-group.component.ts
>    @Input() border: BorderDirectionType;
Maybe you can already set a default border value here.

```suggestion
  @Input() border: BorderDirectionType = 'bottom';
```

2023-04-14 17:28 UTC, mizek1 commented on projects/ion/src/lib/tab-group/tab-group.component.ts
>      return directions[direction] as BorderDirectionType;
Same here:

```
   const directions: { [key in DirectionType]: BorderDirectionType } = {
      horizontal: 'bottom',
      vertical: 'right',
    };

    if (this.isBorderDirectionCorrect(direction)) {
      return this.border;
    }

    return directions[direction];
```

2023-06-01 16:21 UTC, iurynogueira approved these changes

2023-06-05 13:06 UTC, mizek1 approved these changes

2023-06-05 13:36 UTC, merged