chore: pull request description template changes (#598)
Brisanet/ion pull request #603
Opened 2023-04-13 19:27 UTC by PedroMiguel7

Adding two new elements to the proposed model.

 The first element added is "Issue Number", which associates the issue number with the title of the pull request. This helps provide context and traceability for proposed changes in the pull request. If there is no associated issue, it is recommended to create one to ensure better organization and issue management. .

![image](https://user-images.githubusercontent.com/93842972/231861665-d57535fa-a382-448c-b869-5a3e548971f3.png)

The second element added is "View Storybook", which provides a link to the Chromatic Storybook that shows the proposed changes. This will help reviewers quickly and easily see the changes in action. Additionally, I've included a guide on how to access the Chromatic link to make the process of verifying changes easier.

![image](https://user-images.githubusercontent.com/93842972/231861580-8c295273-de21-454a-99f7-1314eaeafff2.png)

2023-04-13 19:47 UTC, iurynogueira requested changes

2023-04-13 19:47 UTC, iurynogueira commented on pull_request_template.md
> +Associate the issue number with the title of the pull request. If you don't have an associated issue, you should create one. Including an issue number helps provide context and traceability to the pr
```suggestion
Associate the issue number with the title of the pull request. If you don't have an associated issue, you should create one. Including an issue number helps provide context and traceability to the proposed changes in the pull request.

fix #issue_number
```

2023-04-14 13:33 UTC, iurynogueira approved these changes

2023-04-14 16:19 UTC, AlyssonMascarenhas approved these changes
great job!

2023-04-14 16:23 UTC, merged