feat: create skeleton component
Brisanet/ion pull request #615
Opened 2023-04-24 16:56 UTC by Yur16

## [518 - Skeleton component](https://github.com/Brisanet/ion/issues/518)

## Description
Implements the sketeleon component with variants

## Screenshot
![ezgif-1-43653373c2](https://user-images.githubusercontent.com/45566439/234062217-d30c8b50-f5be-4108-867a-8fad174b21fc.gif)

## Compliance
- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code.

2023-04-24 20:25 UTC, iurynogueira commented
ℹ View your Storybook at https://62eab350a45bdb0a5818520e-eabbtxpfgj.chromatic.com/

2023-04-24 20:33 UTC, iurynogueira requested changes
Thanks for your contribution @Yur16

2023-04-24 20:33 UTC, iurynogueira commented on projects/ion/src/lib/skeleton/skeleton.component.spec.ts
> +    const skeleton = screen.getByTestId('ion-skeleton');
```suggestion
    const skeleton = screen.getByTestId('ion-skeleton');
```

You can create a function to return this element

2023-04-24 20:33 UTC, iurynogueira commented on projects/ion/src/lib/skeleton/skeleton.component.spec.ts
> +    expect(skeleton).toHaveStyle('border-radius: 12px');
```suggestion
    expect(getSkeleton()).toHaveStyle('border-radius: 12px');
```

and use here

2023-04-24 20:33 UTC, iurynogueira commented on projects/ion/src/lib/skeleton/skeleton.component.html
> +  [style.borderRadius]="getRadius()"
call a function here can come lose performance, my suggestion is add your logic here

2023-04-25 13:14 UTC, iurynogueira approved these changes
![uhul](https://user-images.githubusercontent.com/6165180/234287651-a5da17f3-b09f-40df-84d3-1cbd221787d2.gif)

2023-04-25 14:04 UTC, jairochaves2 approved these changes

2023-04-25 14:19 UTC, merged