447 popover in indicator component
Brisanet/ion pull request #705
Opened 2023-06-14 18:24 UTC by jAllanOli

## Issue Number

fix #447 

## Description

The indicator component should have a option to open a popover, so I added a button with the popover directive that will be rendered when the type popover is informed, and also implemented the popover input properties on the indicator template so the indicator can pass it to the popover.

## Proposed Changes

- Changed the logic of the HTML, so the button will be conditionally rendered; 
- changed the indicator type, so it can receive the popover props and the actions callbacks;
- created a new mock component and a story to visualise the implementation; 
- implemented new test assertions to ensure that the rendering will work as expected.

## How to Test

run yarn test indicator or check the story "Indicator: with popover" of the storybook.

## Screenshots

Include screenshots or GIFs that illustrate the proposed changes. This can be especially useful for user interface changes.

## View Storybook

Provide a link to the chromatic Storybook that shows the proposed changes so reviewers can easily see the changes in action.

Please also be aware that in addition to the Chromatic link, the link in the pull request description will also need to be updated whenever changes are made.

<details>
  <summary>How can I access the Chromatic link?</summary>

- Open the pull request that you wish to verify the Storybook Chromatic on.

- At the bottom of the "Checks" comment, click on "Details" next to the "Chromatic/chromatic-deployment" status.

- On the "Checks" page, you will see a list of checks. Select the "Publish to Chromatic" section.

- Scroll down until you find the section "View your Storybook at https://examplelink", that represents the desired link.

</details>

## Compliance

- [X] I have verified that this change complies with our code and contribution policies.
- [X] I have verified that this change does not cause regressions and does not affect other parts of the code.

2023-06-14 19:03 UTC, iurynogueira requested changes

2023-06-14 19:03 UTC, iurynogueira commented on stories/IndicatorPopover.stories.ts
> +const Template: Story<IndicatorPopoverComponent> = (
Add this case in Indicator doc

2023-06-14 19:05 UTC, iurynogueira commented
Nice work @jAllanOli, this issue are relevant and wasn't easy

2023-06-14 19:44 UTC, iurynogueira approved these changes

2023-06-15 12:25 UTC, Deeved approved these changes

2023-06-15 12:50 UTC, merged