docs: add example img of custom row on table docs #738
Brisanet/ion pull request #750
Opened 2023-07-14 15:04 UTC by MadalenaCampos

#738

2023-07-26 11:44 UTC, iurynogueira approved these changes

2023-07-26 12:41 UTC, Deeved approved these changes

2023-07-27 13:42 UTC, iurynogueira commented
Storybook: https://62eab350a45bdb0a5818520e-dhxccczyxx.chromatic.com/

2023-07-27 13:54 UTC, iurynogueira requested changes
SmartTable docs not showing.

2023-07-28 18:36 UTC, iurynogueira approved these changes

2023-07-28 18:40 UTC, merged