feat: adding close when options is selected behavior (#834)
Brisanet/ion pull request #836
Opened 2023-09-22 13:16 UTC by larissa-kamily-brisa

## Issue Number
feat #834  

## Description
Now the Ion sidebar has a behavior of closing the sidebar when an option is selected, improving the customer experience

## Screenshots
[Gravação de tela de 2023-09-22 10-10-48.webm](https://github.com/Brisanet/ion/assets/138057627/e68b08f8-02a8-412f-a331-a5957ebebb1b)

## View Storybook

- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code[Gravação de tela de

2023-09-22 13:55 UTC, alysson-mascarenhas-brisa approved these changes

2023-09-25 11:47 UTC, iurynogueira requested changes

2023-09-25 11:47 UTC, iurynogueira commented on projects/ion/src/lib/sidebar/sidebar.component.ts
> +    this.closeOnSelect ? this.toggleSidebarVisibility() : false;
You not need a ternary here.
```suggestion
    if (this.closeOnSelect ) {
      this.toggleSidebarVisibility()
    }
```

2023-09-25 11:47 UTC, iurynogueira commented on projects/ion/src/lib/sidebar/sidebar.component.ts
> +    this.closeOnSelect ? this.toggleSidebarVisibility() : false;
same think

2023-09-25 18:03 UTC, iurynogueira approved these changes

2023-09-25 18:03 UTC, iurynogueira commented
Check coverage

2023-09-28 17:00 UTC, merged