Add alert variation with description
Brisanet/ion pull request #839
Opened 2023-09-26 13:20 UTC by madalena-campos-brisa

Two properties were added:
description: Validates the use of description in the alert;
noRadius: Allows the removal of the alert's border-radius.

It was necessary to change the structure of the alert, but visually it is the same.

2023-09-27 14:30 UTC, allan-chagas-brisa requested changes

2023-09-27 17:23 UTC, iurynogueira requested changes

2023-09-27 17:23 UTC, iurynogueira commented on projects/ion/src/lib/alert/alert.component.spec.ts
> +  });
create a new test case to when have radius, with noRadius false.

2023-09-27 20:01 UTC, allan-chagas-brisa requested changes

2023-09-27 20:01 UTC, allan-chagas-brisa commented on projects/ion/src/lib/alert/alert.component.html
> +  </div>
```suggestion
  <span *ngIf="description?.length > 0" class="description">
    {{ description }}
  </span>
```
It remained a div.

2023-09-28 11:05 UTC, allan-chagas-brisa commented on projects/ion/src/lib/alert/alert.component.scss
> +    hyphens: auto;
I think I removed these properties when submited the review, you can see on the other comment.

2023-09-28 11:05 UTC, allan-chagas-brisa commented on projects/ion/src/lib/alert/alert.component.scss
> +  padding: 16px 24px !important;
sorry, forgot to sugest the sass functions.
```suggestion
  padding: spacing(2) spacing(3) !important;
```

2023-09-28 12:43 UTC, allan-chagas-brisa approved these changes
Nice :)

2023-09-29 13:04 UTC, iurynogueira approved these changes

2023-09-29 13:06 UTC, merged