Add new "Collapse" component with customizable Inputs
Brisanet/ion pull request #851
Opened 2023-09-28 23:09 UTC by deeved-hiuston-brisa

## Issue Number

#849 

## Description

This Pull Request aims to add a new component called "Collapse" to our project. The "Collapse" component provides the ability to hide and show content with a collapse/expand feature. It comes with a set of customizable Inputs for greater usage flexibility.

## Proposed Changes

1. Addition of the "Collapse" component to the components directory.
2. Definition of the following Inputs for the "Collapse" component:
- @Input() name?: string;: This Input allows associating a name with the component, making it more identifiable and useful in contexts where multiple "Collapse" components may be used.
- @Input() templateHeader: TemplateHeader;: This Input allows providing a custom TemplateHeader for the header of the "Collapse" component, giving the freedom to customize the header's appearance.
- @Input() show? = false;: This Input controls the display state of the content within the "Collapse" component. When set to true, the content is displayed; otherwise, it remains hidden by default.
- @Input() color?: string;: This Input allows specifying a custom color for the "Collapse" component's header, enabling a more flexible visual appearance.
3. Creation of unit tests to ensure the correct functioning of the "Collapse" component and its customizable Inputs.
4. Addition of comprehensive documentation using Storybook for the "Collapse" component, demonstrating how to use it with examples and usage scenarios.

## Motivation

The addition of this new "Collapse" component with customizable Inputs will enhance the flexibility and usability of our project, enabling developers to create more dynamic and appealing user interfaces.

## How to Test

To test the "Collapse" component, please follow the instructions in the Storybook and utilize the provided unit tests in this Pull Request.

## View Storybook

2023-09-29 12:11 UTC, alysson-mascarenhas-brisa approved these changes
It was very good and easy to use. Congratulations on the work!

2023-10-03 13:32 UTC, iurynogueira requested changes
Nice!

2023-10-03 13:32 UTC, iurynogueira commented on projects/ion/src/lib/accordion/accordion.component.spec.ts
> +  });
```suggestion
  it('should render ion-accordion with name Brisanet', async () => {
    const accordionName = 'Brisanet';
    accordionTestComponent.name = accordionName ;
    fixture.detectChanges();
    expect(screen.getByTestId('ion-accordion__header-name')).toHaveTextContent(
      accordionName 
    );
  });
```

2023-10-03 13:32 UTC, iurynogueira commented on projects/ion/src/lib/accordion/accordion.component.ts
> +  @Input() templateHeader: TemplateHeader;
```suggestion
  @Input() templateHeader?: TemplateHeader;
```

2023-10-03 14:01 UTC, deeved-hiuston-brisa commented on projects/ion/src/lib/accordion/accordion.component.html
Thanks for the tip! :heart:

2023-10-03 16:53 UTC, deeved-hiuston-brisa commented on projects/ion/src/lib/accordion/accordion.component.html
> +    <ion-icon *ngIf="show" type="semi-down" [size]="iconSize"></ion-icon>
True. Thanks for the observation. :smile:

2023-10-03 17:05 UTC, iurynogueira approved these changes

2023-10-03 17:05 UTC, allan-chagas-brisa commented on projects/ion/src/lib/accordion/accordion.component.html
> +    <ion-icon *ngIf="show" type="semi-down" [size]="iconSize"></ion-icon>
No worries :D

2023-10-06 12:23 UTC, merged