fix: select an option when there are several radio-group
Brisanet/ion pull request #882
Opened 2023-10-18 14:36 UTC by deeved-hiuston-brisa

## Issue Number

fix #881 

## Description

This PR proposes to fix the following issue: when you have more than one radio-group on the screen and select an option by clicking on a label that does not belong to the first group, an option from the first group is always selected.

## Proposed Changes

- The name of the radio-group was added to the option id (radio);
- Test adaptation.

## Screenshots

### Problem

https://github.com/Brisanet/ion/assets/138057453/c6a445cd-0e18-4324-aba8-70b803b46342

### Corretion

https://github.com/Brisanet/ion/assets/138057453/dbe263da-6dcb-4762-bfd3-c0fff67e0f5f

2023-10-18 17:30 UTC, iurynogueira requested changes

2023-10-23 16:52 UTC, iurynogueira approved these changes
Very well!

2023-10-23 16:52 UTC, iurynogueira commented on projects/ion/src/lib/radio-group/radio-group.component.spec.ts
> +    expect(languageOptions[0]).toBeChecked();
```suggestion
    const optionToSelect = languageOptions[0];
    const htmlOption = screen.getByLabelText(optionToSelect.label);
    fireEvent.click(htmlOption);
    expect(optionToSelect).toBeChecked();
```

2023-10-24 12:59 UTC, alysson-mascarenhas-brisa approved these changes

2023-10-26 12:56 UTC, merged