change icon indicator name #963
Brisanet/ion pull request #964
Opened 2023-11-30 04:59 UTC by sfazli96

## Issue Number
#963

fix #issue_number
#963

## Description
I believe I changed the icon where it says information to the icon

## Proposed Changes
modified file card.component.html and line 13

- Open the pull request that you wish to verify the Storybook Chromatic on.

- At the bottom of the "Checks" comment, click on "Details" next to the "Chromatic/chromatic-deployment" status.

- On the "Checks" page, you will see a list of checks. Select the "Publish to Chromatic" section.

- Scroll down until you find the section "View your Storybook at https://examplelink", that represents the desired link.

</details>

## Compliance

- [✓ ] I have verified that this change complies with our code and contribution policies.
- [✓ ] I have verified that this change does not cause regressions and does not affect other parts of the code.

## Concluding

Remember that the goal of this template is to provide guidance and facilitate communication between developers, so feel free to include any additional information that you find useful. Make sure to check the project's policies and guidelines before submitting the pull request.

2023-11-30 12:49 UTC, allan-chagas-brisa commented
Actually, this isn't the right component, the issue refers to the [indicator component](https://github.com/Brisanet/ion/tree/main/projects/ion/src/lib/indicator).

2023-12-01 11:50 UTC, iurynogueira requested changes

2023-12-01 11:50 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.html
> +        type="information"
here you can keep `type="icon"`

2023-12-01 11:50 UTC, iurynogueira commented on projects/ion/src/lib/indicator/indicator.component.html
> +        type="information"
👍

2023-12-07 18:14 UTC, merged